
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from .schemas import RetinalAnalysisResponse

class ReportGenerator:
    """
    Generates clinical PDFs for Retinal Analysis.
    """

    def generate_report(self, assessment: RetinalAnalysisResponse) -> bytes:
        """
        Generate a PDF report for the given assessment.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # 1. Header
        story.append(Paragraph(f"NeuroLens Retinal Assessment Report", styles['Title']))
        story.append(Spacer(1, 12))
        
        # 2. Patient & Metadata
        meta_data = [
            ["Patient ID:", assessment.patient_id],
            ["Assessment ID:", assessment.assessment_id],
            ["Date:", assessment.created_at.strftime("%Y-%m-%d %H:%M:%S")],
            ["Model Version:", assessment.model_version],
        ]
        t_meta = Table(meta_data, colWidths=[100, 300])
        t_meta.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(t_meta)
        story.append(Spacer(1, 20))

        # 3. Risk Assessment
        risk = assessment.risk_assessment
        risk_color = colors.green if risk.risk_category in ["minimal", "low"] else colors.red
        
        story.append(Paragraph(f"Risk Assessment: {risk.risk_category.upper()}", styles['Heading2']))
        story.append(Paragraph(f"Risk Score: {risk.risk_score} / 100", styles['Normal']))
        story.append(Spacer(1, 12))

        # 4. Biomarkers Table
        biomarker_data = [
            ["Biomarker", "Value", "Confidence"],
            ["Vessel Density", f"{assessment.biomarkers.vessels.density_percentage:.1f}%", f"{assessment.biomarkers.vessels.confidence:.2f}"],
            ["Vessel Tortuosity", f"{assessment.biomarkers.vessels.tortuosity_index:.2f}", "-"],
            ["Cup-to-Disc Ratio", f"{assessment.biomarkers.optic_disc.cup_to_disc_ratio:.2f}", f"{assessment.biomarkers.optic_disc.confidence:.2f}"],
            ["Macular Thickness", f"{assessment.biomarkers.macula.thickness_um:.1f} um", f"{assessment.biomarkers.macula.confidence:.2f}"],
            ["Amyloid Presence", f"{assessment.biomarkers.amyloid_beta.presence_score:.2f}", f"{assessment.biomarkers.amyloid_beta.confidence:.2f}"],
        ]
        
        t_bio = Table(biomarker_data)
        t_bio.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(t_bio)
        story.append(Spacer(1, 20))

        # 5. Recommendations
        story.append(Paragraph("Clinical Recommendations", styles['Heading2']))
        rec_text = "Based on the analysis, consider the following next steps:"
        if risk.risk_score > 50:
            rec_text += " Immediate follow-up with a specialist is recommended due to elevated risk markers."
        else:
            rec_text += " Routine monitoring is advised. No immediate intervention required."
        story.append(Paragraph(rec_text, styles['Normal']))

        # 6. Disclaimer
        story.append(Spacer(1, 30))
        disclaimer = "DISCLAIMER: This report is generated by an AI screening tool and is NOT a definitive medical diagnosis. All results should be reviewed by a qualified ophthalmologist or neurologist."
        story.append(Paragraph(disclaimer, ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

report_generator = ReportGenerator()
