"""enhance_patient_schema

Revision ID: 5ee9a46e159f
Revises: b2b36a1441e6
Create Date: 2026-01-22 02:14:37.270255+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee9a46e159f'
down_revision: Union[str, None] = 'b2b36a1441e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('insurance_provider', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('medical_history', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('medications', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('family_history', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('assigned_doctor_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    op.create_index(op.f('ix_patients_assigned_doctor_id'), 'patients', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'users', ['assigned_doctor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patients', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_assigned_doctor_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('patients', 'deleted_at')
    op.drop_column('patients', 'last_visit_at')
    op.drop_column('patients', 'assigned_doctor_id')
    op.drop_column('patients', 'organization_id')
    op.drop_column('patients', 'family_history')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'medications')
    op.drop_column('patients', 'medical_history')
    op.drop_column('patients', 'insurance_policy_number')
    op.drop_column('patients', 'insurance_provider')
    op.drop_column('patients', 'emergency_contact')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'date_of_birth')
    # ### end Alembic commands ###
