"""link_assessment_to_patient

Revision ID: 6553f0524bec
Revises: 5ee9a46e159f
Create Date: 2026-01-22 02:23:07.764869+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6553f0524bec'
down_revision: Union[str, None] = '5ee9a46e159f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
