"""Initial_schema_setup

Revision ID: d3a272c8593e
Revises: 
Create Date: 2026-01-21 23:37:56.545845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a272c8593e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_type', sa.String(length=50), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_created_at'), 'assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assessments_pipeline_type'), 'assessments', ['pipeline_type'], unique=False)
    op.create_index(op.f('ix_assessments_requires_review'), 'assessments', ['requires_review'], unique=False)
    op.create_index(op.f('ix_assessments_session_id'), 'assessments', ['session_id'], unique=True)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_ip', postgresql.INET(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('hipaa_relevant', sa.Boolean(), nullable=True),
    sa.Column('phi_accessed', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_hipaa_relevant'), 'audit_events', ['hipaa_relevant'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_is_active'), 'chat_threads', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_threads_last_message_at'), 'chat_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('fitzpatrick_type', sa.SmallInteger(), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('medical_history', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('consent_research', sa.Boolean(), nullable=True),
    sa.Column('consent_data_sharing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('voice_generated', sa.Boolean(), nullable=True),
    sa.Column('voice_url', sa.Text(), nullable=True),
    sa.Column('voice_duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanations_assessment_id'), 'ai_explanations', ['assessment_id'], unique=False)
    op.create_table('biomarker_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('biomarker_name', sa.String(length=100), nullable=False),
    sa.Column('biomarker_category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('normal_range_min', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('normal_range_max', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('percentile', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomarker_values_assessment_id'), 'biomarker_values', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_biomarker_values_biomarker_category'), 'biomarker_values', ['biomarker_category'], unique=False)
    op.create_index(op.f('ix_biomarker_values_biomarker_name'), 'biomarker_values', ['biomarker_name'], unique=False)
    op.create_table('cardiology_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('rhythm_classification', sa.String(length=50), nullable=True),
    sa.Column('heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('regularity', sa.String(length=20), nullable=True),
    sa.Column('r_peaks_detected', sa.Integer(), nullable=True),
    sa.Column('rmssd_ms', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('sdnn_ms', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('pnn50_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('pr_interval_ms', sa.SmallInteger(), nullable=True),
    sa.Column('qrs_duration_ms', sa.SmallInteger(), nullable=True),
    sa.Column('qt_interval_ms', sa.SmallInteger(), nullable=True),
    sa.Column('qtc_ms', sa.SmallInteger(), nullable=True),
    sa.Column('arrhythmia_detected', sa.Boolean(), nullable=True),
    sa.Column('arrhythmia_types', sa.JSON(), nullable=True),
    sa.Column('signal_quality_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_cardiology_results_arrhythmia_detected'), 'cardiology_results', ['arrhythmia_detected'], unique=False)
    op.create_index(op.f('ix_cardiology_results_rhythm_classification'), 'cardiology_results', ['rhythm_classification'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('cognitive_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('overall_risk_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('attention_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('memory_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('executive_function_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('processing_speed_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('valid_tasks', sa.Integer(), nullable=True),
    sa.Column('fatigue_index', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('consistency_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_cognitive_results_risk_level'), 'cognitive_results', ['risk_level'], unique=False)
    op.create_table('dermatology_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('primary_classification', sa.String(length=100), nullable=True),
    sa.Column('melanoma_suspicion', sa.String(length=50), nullable=True),
    sa.Column('asymmetry_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('border_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('color_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('diameter_mm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('evolution_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('body_location', sa.String(length=50), nullable=True),
    sa.Column('fitzpatrick_type', sa.SmallInteger(), nullable=True),
    sa.Column('image_quality', sa.String(length=20), nullable=True),
    sa.Column('lesion_centered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_dermatology_results_melanoma_suspicion'), 'dermatology_results', ['melanoma_suspicion'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('stage_index', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stage_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_assessment_id'), 'pipeline_stages', ['assessment_id'], unique=False)
    op.create_table('radiology_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('modality_type', sa.String(length=50), nullable=True),
    sa.Column('primary_condition', sa.String(length=100), nullable=True),
    sa.Column('primary_probability', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('primary_severity', sa.String(length=20), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('lungs_status', sa.String(length=20), nullable=True),
    sa.Column('heart_status', sa.String(length=20), nullable=True),
    sa.Column('image_quality', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_radiology_results_modality_type'), 'radiology_results', ['modality_type'], unique=False)
    op.create_index(op.f('ix_radiology_results_primary_condition'), 'radiology_results', ['primary_condition'], unique=False)
    op.create_table('retinal_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dr_grade', sa.SmallInteger(), nullable=True),
    sa.Column('dr_severity', sa.String(length=20), nullable=True),
    sa.Column('eye_laterality', sa.String(length=10), nullable=True),
    sa.Column('image_quality', sa.String(length=20), nullable=True),
    sa.Column('four_two_one_met', sa.Boolean(), nullable=True),
    sa.Column('hemorrhages_4_quadrants', sa.Boolean(), nullable=True),
    sa.Column('venous_beading_2_quadrants', sa.Boolean(), nullable=True),
    sa.Column('irma_1_quadrant', sa.Boolean(), nullable=True),
    sa.Column('dme_present', sa.Boolean(), nullable=True),
    sa.Column('dme_severity', sa.String(length=20), nullable=True),
    sa.Column('vessel_density', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('av_ratio', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('tortuosity_index', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('hemorrhage_count', sa.Integer(), nullable=True),
    sa.Column('microaneurysm_count', sa.Integer(), nullable=True),
    sa.Column('exudate_area_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('heatmap_data', sa.JSON(), nullable=True),
    sa.Column('vessel_segmentation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_retinal_results_eye_laterality'), 'retinal_results', ['eye_laterality'], unique=False)
    op.create_table('speech_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('audio_quality_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('jitter', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('shimmer', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('hnr', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('cpps', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('speech_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('pause_ratio', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('voice_tremor', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('articulation_clarity', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('prosody_variation', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('fluency_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('parkinsons_probability', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('cognitive_decline_probability', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_speech_results_audio_quality_score'), 'speech_results', ['audio_quality_score'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_assessment_id'), 'uploaded_files', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_file_hash'), 'uploaded_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_hash'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_assessment_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_speech_results_audio_quality_score'), table_name='speech_results')
    op.drop_table('speech_results')
    op.drop_index(op.f('ix_retinal_results_eye_laterality'), table_name='retinal_results')
    op.drop_table('retinal_results')
    op.drop_index(op.f('ix_radiology_results_primary_condition'), table_name='radiology_results')
    op.drop_index(op.f('ix_radiology_results_modality_type'), table_name='radiology_results')
    op.drop_table('radiology_results')
    op.drop_index(op.f('ix_pipeline_stages_assessment_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_dermatology_results_melanoma_suspicion'), table_name='dermatology_results')
    op.drop_table('dermatology_results')
    op.drop_index(op.f('ix_cognitive_results_risk_level'), table_name='cognitive_results')
    op.drop_table('cognitive_results')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_cardiology_results_rhythm_classification'), table_name='cardiology_results')
    op.drop_index(op.f('ix_cardiology_results_arrhythmia_detected'), table_name='cardiology_results')
    op.drop_table('cardiology_results')
    op.drop_index(op.f('ix_biomarker_values_biomarker_name'), table_name='biomarker_values')
    op.drop_index(op.f('ix_biomarker_values_biomarker_category'), table_name='biomarker_values')
    op.drop_index(op.f('ix_biomarker_values_assessment_id'), table_name='biomarker_values')
    op.drop_table('biomarker_values')
    op.drop_index(op.f('ix_ai_explanations_assessment_id'), table_name='ai_explanations')
    op.drop_table('ai_explanations')
    op.drop_table('user_roles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_last_message_at'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_is_active'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_hipaa_relevant'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_session_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_requires_review'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_pipeline_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_at'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
