"""add_patient_management

Revision ID: b2b36a1441e6
Revises: d3a272c8593e
Create Date: 2026-01-22 00:33:02.203316+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b36a1441e6'
down_revision: Union[str, None] = 'd3a272c8593e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    op.add_column('assessments', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_assessments_patient_id'), 'assessments', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.add_column('uploaded_files', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_uploaded_files_patient_id'), 'uploaded_files', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'uploaded_files', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_index(op.f('ix_uploaded_files_patient_id'), table_name='uploaded_files')
    op.drop_column('uploaded_files', 'patient_id')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_patient_id'), table_name='assessments')
    op.drop_column('assessments', 'patient_id')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
